# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: New Hampshire Psychiatric Society
email: robertfeder1@gmail.com
description: "NHPS is the official voice of organized psychiatry in New Hampshire. Founded in 1972, NHPS is a District Branch of the American Psychiatric Association, the national medical specialty society for 40,000 physician members, and the official voice of Psychiatry in the United States. NHPS is devoted to promoting the highest standards of care for the treatment of mental illness and substance abuse in New Hampshire."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nhpsych.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
